# Telegram Bot Configuration
telegram:
  bot:
    username: "@palastrov_study_bot"
    token: ${TELEGRAM_TOKEN}
    path: "https://6yyfcl-62-113-87-149.ru.tuna.am"

  # Spring Configuration
spring:
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
profiles:
  active: dev

  server:
    port: 8080